### ISSUE TITLE
Rename repository ?

### ISSUE THREAD

**Issue by emdupre** [Brainhack-BayArea/Brainhack-BayArea.github.io#4]
Wondering if we should rename the repository ?

If we name it to Brainhack-BayArea.github.io , there's a special convention where it will live directly at that URL. GitHub is also clever about handling repo renaming and URL redirects under the hood.

What do you think ?

**Comment by demidenm** [comment]
No opposition from me. @mnoergaard can correct me, but I think the naming was due to so issue with the web URL being `Brainhack-BayArea.github.io.Brainhack-BayArea.github.io` 🦝

**Comment by mnoergaard** [comment]
Done :-) https://brainhack-bayarea.github.io/
